apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-monkey
  labels:
    app: kube-monkey
spec:
  selector:
    matchLabels:
      app: kube-monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-monkey
    spec:
      serviceAccountName: kube-monkey-sa
      containers:
        -  name: kube-monkey
           command:
             - "/kube-monkey"
           args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
           image: ayushsobti/kube-monkey:v0.3.0
           volumeMounts:
             - name: config-volume
               mountPath: "/etc/kube-monkey"
      volumes:
        - name: config-volume
          configMap:
            name: km-config
